SELECT 
    TABLE_NAME, 
    TABLE_TYPE, 
    ROW_COUNT, 
    BYTE_LENGTH_TO_STRING(TABLE_BYTES) AS SIZE_HUMAN_FORMAT, 
    (SELECT COUNT(DISTINCT PARTITION_ORDINAL) FROM TABLE_STORAGE_METRICS WHERE TABLE_ID = T.TABLE_ID) AS PARTITION_COUNT
FROM 
    INFORMATION_SCHEMA.TABLES T
LEFT JOIN 
    TABLE_STORAGE_METRICS M 
    ON T.TABLE_CATALOG = M.TABLE_CATALOG 
    AND T.TABLE_SCHEMA = M.TABLE_SCHEMA 
    AND T.TABLE_NAME = M.TABLE_NAME
WHERE 
    T.TABLE_SCHEMA = '<YourSchemaName>'
ORDER BY 
    TABLE_NAME;
